export const notifications = [
  {
    id: 1,
    title: "Your order is placed",
    role: "Frontend Developer",
    desc: "Amet minim mollit non deser unt ullamco est sit aliqua.",
    avatar: "https://i.pravatar.cc/150?img=1",
    status: "online",
    unread_message: false,
    type: "text",
    date: "2 days ago",
  },
  {
    id: 2,
    title: "Congratulations Darlene  🎉",
    role: "UI/UX Designer",
    desc: "Won the monthly best seller badge",
    avatar: "https://i.pravatar.cc/150?img=2",
    status: "online",
    unread_message: true,
    type: "text",
    date: "11 am",
  },
  {
    id: 3,
    title: "Joaquina Weisenborn",
    role: "Town planner",
    desc: "Requesting access permission",
    avatar: "https://i.pravatar.cc/150?img=3",
    status: "busy",
    unread_message: true,
    type: "confirm",
    date: "12 pm",
  },
  {
    id: 4,
    title: "Brooklyn Simmons",
    role: "Data scientist",
    desc: "Added you to Top Secret Project group...",
    avatar: "https://i.pravatar.cc/150?img=4",
    status: "online",
    unread_message: true,
    type: "text",
    date: "1 pm",
  },
  {
    id: 5,
    title: "Margot Henschke",
    role: "Dietitian",
    desc: "Cake pie jelly jelly beans. Marzipan lemon drops halvah cake. Pudding cookie lemon drops icing",
    avatar: "https://i.pravatar.cc/150?img=5",
    status: "busy",
    unread_message: false,
    type: "text",
    date: "3 pm",
  },
] as const;

export type Notification = (typeof notifications)[number];
